In [23]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/yelp_academic_dataset_business.json
/kaggle/input/Dataset_Agreement.pdf
/kaggle/input/yelp_academic_dataset_tip.json
/kaggle/input/yelp_academic_dataset_review.json
/kaggle/input/yelp_academic_dataset_checkin.json
/kaggle/input/yelp_academic_dataset_user.json

In [24]:
import json

def load_rows(filepath, nrows = None):
    with open(filepath) as json_file:
        count = 0
        objs = []
        line = json_file.readline()
        while (nrows is None or count < nrows) and line:
            count += 1
            obj = json.loads(line)
            objs.append(obj)
            line = json_file.readline()
        return pd.DataFrame(objs)

In [25]:
business = load_rows('/kaggle/input/yelp_academic_dataset_business.json',10000)
print('Business objects loaded. Count = {}'.format(business.shape[0]))

tip = load_rows('/kaggle/input/yelp_academic_dataset_tip.json',10000)
print('tip objects loaded. Count = {}'.format(tip.shape[0]))

user = load_rows('/kaggle/input/yelp_academic_dataset_user.json',10000)
print('user objects loaded. Count = {}'.format(user.shape[0]))

review = load_rows('/kaggle/input/yelp_academic_dataset_review.json',10000)
print('checkin objects loaded. Count = {}'.format(review.shape[0]))

checkin = load_rows('/kaggle/input/yelp_academic_dataset_checkin.json',10000)
print('checkin objects loaded. Count = {}'.format(checkin.shape[0]))

Business objects loaded. Count = 10000
tip objects loaded. Count = 10000
user objects loaded. Count = 10000
checkin objects loaded. Count = 10000
checkin objects loaded. Count = 10000

In [26]:
business.iloc[100]

business_id                                JcsZvx-4yovFgCXOfd6KMg
name                                              Sam's Deli Mart
address                                   3300 N Central Ave Lbby
city                                                      Phoenix
state                                                          AZ
postal_code                                                 85012
latitude                                                  33.6483
longitude                                                -112.119
stars                                                           3
review_count                                                    4
is_open                                                         0
attributes      {'RestaurantsTakeOut': 'True', 'RestaurantsGoo...
categories                                Restaurants, Sandwiches
hours                                                        None
Name: 100, dtype: object

In [27]:
user.head()

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,ntlvfPzc8eglqvk92iDIAw,Rafael,553,2007-07-06 03:27:11,628,225,227,,"oeMvJh94PiGQnx_6GlndPQ, wm1z1PaJKvHgSDRKfwhfDg...",14,...,2,1,0,1,11,15,22,22,10,0
1,FOBRPlBHa3WPHFB5qYDlVg,Michelle,564,2008-04-28 01:29:25,790,316,400,"2008,2009,2010,2011,2012,2013","ly7EnE8leJmyqyePVYFlug, pRlR63iDytsnnniPb3AOug...",27,...,4,5,2,1,33,37,63,63,21,5
2,zZUnPeh2hEp0WydbAZEOOg,Martin,60,2008-08-28 23:40:05,151,125,103,2010,"Uwlk0txjQBPw_JhHsQnyeg, Ybxr1tSCkv3lYA0I1qmnPQ...",5,...,6,0,1,0,3,7,17,17,4,1
3,QaELAmRcDc5TfJEylaaP8g,John,206,2008-09-20 00:08:14,233,160,84,2009,"iog3Nyg1i4jeumiTVG_BSA, M92xWY2Vr9w0xoH8bPplfQ...",6,...,1,0,0,0,7,14,7,7,2,0
4,xvu8G900tezTzbbfqmTKvA,Anne,485,2008-08-09 00:30:27,1265,400,512,"2009,2010,2011,2012,2014,2015,2016,2017,2018","3W3ZMSthojCUirKEqAwGNw, eTIbuu23j9tOgmIa9POyLQ...",78,...,9,2,1,1,22,28,31,31,19,31

In [28]:
review.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,xQY8N_XvtGbearJ5X4QryQ,OwjRMXRC0KyPrIlcjaXeFQ,-MhfebM0QIsKt87iDN-FNw,2.0,5,0,0,"As someone who has worked with many museums, I...",2015-04-15 05:21:16
1,UmFMZ8PyXZTY2QcwzsfQYA,nIJD_7ZXHq-FX8byPMOkMQ,lbrU8StCq3yDfr-QMnGrmQ,1.0,1,1,0,I am actually horrified this place is still in...,2013-12-07 03:16:52
2,LG2ZaYiOgpr2DK_90pYjNw,V34qejxNsCbcgD8C0HVk-Q,HQl28KMwrEKHqhFrrDqVNQ,5.0,1,0,0,I love Deagan's. I do. I really do. The atmosp...,2015-12-05 03:18:11
3,i6g_oA9Yf9Y31qt0wibXpw,ofKDkJKXSKZXu5xJNGiiBQ,5JxlZaqCnk1MnbgRirs40Q,1.0,0,0,0,"Dismal, lukewarm, defrosted-tasting ""TexMex"" g...",2011-05-27 05:30:52
4,6TdNDKywdbjoTkizeMce8A,UgMW8bLE0QMJDCkQ1Ax5Mg,IS4cv902ykd8wj1TR0N3-A,4.0,0,0,0,"Oh happy day, finally have a Canes near my cas...",2017-01-14 21:56:57

In [29]:
business_all = load_rows('/kaggle/input/yelp_academic_dataset_business.json')

In [30]:
print('Business objects loaded. Count = {}'.format(business_all.shape[0]))

Business objects loaded. Count = 209393

In [31]:
city = business.groupby('city')["business_id"].agg({'size'}).sort_values(ascending=False, by = 'size').reset_index().loc[0:10]

In [32]:
city.head()

         city  size
0   Las Vegas  1610
1     Toronto   959
2     Phoenix   943
3   Charlotte   487
4  Scottsdale   469

In [33]:
city[city['city'] == 'Toronto']

      city  size
1  Toronto   959

In [34]:
city_all = business_all.groupby('city')["business_id"].agg({'size'}).sort_values(ascending=False, by = 'size').reset_index()

In [35]:
city_all

                city   size
0          Las Vegas  31631
1            Toronto  20366
2            Phoenix  20171
3          Charlotte  10422
4         Scottsdale   9342
...              ...    ...
1246     Queensville      1
1247      Huntingdon      1
1248     ROCKY RIVER      1
1249  Rainbow Valley      1
1250        ​Gilbert      1

[1251 rows x 2 columns]

In [36]:
business.isnull().values.any()

True

In [37]:
business.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,f9NumwFMBDn751xgFiRbNA,The Range At Lake Norman,10913 Bailey Rd,Cornelius,NC,28031,35.462724,-80.852612,3.5,36,1,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Active Life, Gun/Rifle Ranges, Guns & Ammo, Sh...","{'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'..."
1,Yzvjg0SayhoZgCljUJRF9Q,"Carlos Santo, NMD","8880 E Via Linda, Ste 107",Scottsdale,AZ,85258,33.569404,-111.890264,5.0,4,1,"{'GoodForKids': 'True', 'ByAppointmentOnly': '...","Health & Medical, Fitness & Instruction, Yoga,...",None
2,XNoUzKckATkOD1hP6vghZg,Felinus,3554 Rue Notre-Dame O,Montreal,QC,H4C 1P4,45.479984,-73.580070,5.0,5,1,None,"Pets, Pet Services, Pet Groomers",None
3,6OAZjbxqM5ol29BuHsil3w,Nevada House of Hose,1015 Sharp Cir,North Las Vegas,NV,89030,36.219728,-115.127725,2.5,3,0,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Hardware Stores, Home Services, Building Suppl...","{'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ..."
4,51M2Kk903DFYI6gnB5I6SQ,USE MY GUY SERVICES LLC,4827 E Downing Cir,Mesa,AZ,85205,33.428065,-111.726648,4.5,26,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Plumbing, Electricians, Handyma...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '..."

In [55]:
attr_check = pd.isnull(business['attributes'])
cati_check = pd.isnull(business['categories'])

In [56]:
business[cati_check]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
141,2W1tLg8ybRUEKMPoAPHTsQ,Cox Media,"6725 Via Austi Pkwy, Ste 100",Las Vegas,NV,89119,36.067270,-115.162840,1.0,3,1,None,None,None
217,oCbk_T5eyc3KB0iT6T5q9w,Criminal Customz,1053 Broadway,Lorain,OH,44052,41.461689,-82.171509,1.0,4,1,None,None,None
293,4YI_gJQuW-8d_o2xvflJxA,Cag Acceptance,2629 N Scottsdale Rd,Scottsdale,AZ,85257,33.477808,-111.925856,1.5,6,1,None,None,None
570,reOlnE49Ug3BMSGn3IAweg,Csorba Tree Experts,2302 Cronemeyer St,McKeesport,PA,15132,40.355388,-79.837862,5.0,3,1,None,None,None
747,KnAV3ZhOWWNhqnvqIkxYOg,Accurate Lien & Contractor Assistance,"6210 E Thomas Rd, Ste 203",Scottsdale,AZ,85251,33.480885,-111.948134,1.5,3,1,None,None,None
1519,pG8D1gthGbMMOj9y1MxOeA,Cub Cadet,5965 Grafton Rd,Valley City,OH,44280,41.260517,-81.894493,1.5,3,1,None,None,None
2097,3stT022u8m1H37mcopGuUA,Flik & Company,989 Queen St E,Toronto,ON,M4M 1K2,43.661290,-79.338943,1.5,4,0,None,None,None
2543,HgJqVPLNI29YJIlYBmScQQ,Ice Man of Arizona Equipment Company,508 W Watkins Rd,Phoenix,AZ,85003,33.426252,-112.080841,2.0,5,1,None,None,None
2869,_lVdg7Tdw-Vkn0dn-gS2qw,Vascular Access Center of Southern Nevada,3150 W Charleston Blvd,Las Vegas,NV,89102,36.159600,-115.184701,4.0,4,1,None,None,None
3616,Fjd69v08ozCbV2qEbWkLCQ,Grant and Weber,,Las Vegas,NV,89101,36.169710,-115.123695,1.0,3,1,None,None,None
5115,oYFUHj8XFM36SdPCoQaXPQ,Austin's Automotive Inspection Service,"10120 Albemarle Rd, Ste B",Charlotte,NC,28227,35.208076,-80.672268,3.5,3,1,None,None,None
5415,8eHUD8OBe2nXaLKV68K0Rw,Fortune Properties,"1601 S Rainbow Blvd, Ste 130",Las Vegas,NV,89146,36.153717,-115.243889,1.0,3,1,None,None,None
5581,_idu2VZT3e2xy1tGx9P4fA,Greenshield Canada,155 Av University,Toronto,ON,M5H 3B7,43.648502,-79.385016,1.0,3,0,None,None,None
5591,5qv5MOZh1UTmj18-5zSusQ,Trugreen Chemlawn,"655 Pressley Rd, Ste R",Charlotte,NC,28217,35.186162,-80.894276,1.0,3,1,None,None,None
6221,IBAvWgl1CX8doybLdA-74g,Peoples Utility,5310 W Sahara Ave,Las Vegas,NV,89146,36.144799,-115.214019,1.0,3,1,None,None,None
6817,pm36bCxGC_hPkLMhiObBDw,Arizona Pipeline Company,3111 W Lincoln St,Phoenix,AZ,85009,33.441364,-112.126787,1.0,3,1,None,None,None
6840,hEQxSi_Mo5xXtSFnK9trSw,City Tin Shop,30 Wilson St NE,Concord,NC,28025,35.416193,-80.575764,3.0,4,1,None,None,None
7080,9dAHyMaKyE1Rzl9U1AKaBQ,Davita #3682,2250 S Rancho Dr,Las Vegas,NV,89102,36.146642,-115.171547,4.0,4,1,None,None,None
7536,rWsoiLQeFy-RCdYtQvH-JA,Budget Rent A Car System,5701 Boulder Hwy,Las Vegas,NV,89122,36.098979,-115.047817,1.0,3,1,None,None,None
7868,BiBTwivxbsVVlNVgj4lduA,M & D Limited,25405 Broadway Ave,Bedford,OH,44146,41.360684,-81.501420,1.0,3,1,None,None,None
8388,GdyCoJ7hXVTI6qQYHOw_ZA,Medicard Finance,60 Bloor Street W,Toronto,ON,M4W 3B8,43.670083,-79.389187,1.0,3,1,None,None,None
8515,kynu0DO6ro1-Sqh0ZN0rNw,Apria Healthcare,,Phoenix,AZ,85003,33.449551,-112.078936,2.0,5,1,None,None,None
9040,CF6fr67K5TL9gXMx-CoGTw,Iyer Natasha Dr,922 5 Avenue SW,Calgary,AB,T2P 5P6,51.049078,-114.082304,2.5,3,1,None,None,None
9156,Wz2eHvL0IVeAEtItGS3aGQ,Modern Closets,"3215 N Arizona Ave, Ste 5",Chandler,AZ,85225,33.351814,-111.840424,1.0,3,1,None,None,None
9908,hifoN6UwnOU-GmAnF87pEQ,Grainger Industrial Supply,1401 S Mint St,Charlotte,NC,28203,35.219583,-80.858622,4.0,4,1,None,None,None

In [57]:
review.isnull().values.any()

False